### ISSUE TITLE
How to implement

### ISSUE THREAD

**Issue by JMCPH** [danielgindi/DGLocationManager#1]
I might ask stupid, but how do you implement this?

Do i have to make a dglocationmanager *locationmanager, and then set the delegate?

**Comment by danielgindi** [comment]
This class is always a singleton. So you can just call [DGLocationManager
addDelegate:...]

And while you are tracking location, you can also access current data
through DGLocationManager.location etc.

**Comment by danielgindi** [comment]
This class is always a singleton. So you can just call `[DGLocationManager addDelegate:...]`

And while you are tracking location, you can also access current data through `DGLocationManager.location` etc.

**Comment by JMCPH** [comment]
Awesome, i'm quite new to all of the iOS world! Thank you!

**Comment by danielgindi** [comment]
NP :-)

**Comment by JMCPH** [comment]
Would it be possible to make the singleton support Region Monitoring? :+1:
